# Generated by Django 5.0.7 on 2024-11-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='re_enter_code',
        ),
    ]
