# Generated by Django 5.0.7 on 2024-11-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_login_re_enter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
