# Generated by Django 5.0.7 on 2024-11-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_login_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
